//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

pub use super::{
    account::Entity as Account, account_goal::Entity as AccountGoal,
    bridge_module_state::Entity as BridgeModuleState,
};

pub use super::{
    account::ActiveModel as AccountActiveModel, account_goal::ActiveModel as AccountGoalActiveModel,
};

pub use super::{account::Model as AccountModel, account_goal::Model as AccountGoalModel};

pub use super::bridge_module_state::{
    ActiveModel as BridgeStateActiveModel, Model as BridgeStateModel,
};
